#!/bin/bash

rm -rf node_modules
rm package-lock.json
# rm packages/academy/tsconfig.tsbuildinfo
# rm packages/event/tsconfig.tsbuildinfo
# rm packages/core/tsconfig.tsbuildinfo

npm install
npm install @nodet2/core -w @nodet2/academy
npm install @nodet2/core -w @nodet2/event

npm run build
npm run build --workspace ./packages/core #This shouldn't be necessary
npm run build --workspace ./packages/academy
npm run build --workspace ./packages/event

npm run lint

npm run test --workspace ./packages/academy

npm run start --workspace ./packages/core
npm run start --workspace ./packages/event
npm run start --workspace ./packages/academy